- hosts: k8s
  gather_facts: no 
  roles:
    - 00-ssh-copy
  tags:
    - prepare

- hosts: k8s
  gather_facts: no
  vars:
    - kubeedge: false
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo 
  roles:
    - 01-install-docker
    - 01-install-kubeadm
  tags:
    - prepare
    
- hosts: k8s-master
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: 02-init-master
      user: ubuntu
  tags:
    - init_master

- hosts: k8s-master
  roles:
    - role: 03-init-helm
      user: ubuntu
  tags:
    - init_helm

- hosts: k8s-worker
  gather_facts: no 
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - 04-join-nodes
  tags:
    - join_nodes
