- name: install docker 1
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent 
    - software-properties-common
  register: output

- name: install docker 2
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: install docker 3  
  shell: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" >> /etc/apt/sources.list

- name: instll docker 4
  apt:
    update_cache: yes
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io