- name: install docker 1
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent 
    - software-properties-common
  register: output

- name: install docker 2
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: install docker 3  
  shell: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" >> /etc/apt/sources.list

- name: instll docker 4
  apt:
    update_cache: yes
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

- name: add docker user
  shell: |
    if [ -z $(egrep "^docker" /etc/group) ];then groupadd docker; fi
    usermod -aG docker ubuntu
    mkdir -p /home/ubuntu/.docker
    chown ubuntu:ubuntu /home/ubuntu/.docker /var/run/docker.sock -R
    chmod g+rwx /home/ubuntu/.docker /var/run/docker.sock -R

- name: restart docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
