- name: install jq
  become: yes
  become_user: root
  become_method: sudo
  apt:
    update_cache: yes
    name: jq

- name: get helm scripts
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get-helm.sh
    force: yes

- name: run helm scripts
  shell: |
    if [ "$(kubectl get nodes -o json | jq '.items[].spec.taints')" != "null" ]; then kubectl taint nodes --all node-role.kubernetes.io/master-; fi
    chmod +x /tmp/get-helm.sh
    /tmp/get-helm.sh