- name: get kubeadm ip
  shell: hostname -i |grep -E -oh '((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])'|head -n 1
  register: kubeadm_ip
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: get kubeadm token
  shell: kubeadm token list | awk '{print $1}' | sed -n '2p'
  register: kubeadm_token
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: get kubeadm ca
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: kubeadm_ca_cert_hash
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: join k8s
  shell: |
    kubeadm join "{{ kubeadm_ip.stdout }}":6443 \
      --token "{{ kubeadm_token.stdout }}" \
      --discovery-token-ca-cert-hash sha256:"{{ kubeadm_ca_cert_hash.stdout }}"
      